services:
  test-db:
    container_name: test-db-container
    image: postgres:15
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
    ports:
      - '5432:5432'
    volumes:
      - ./data-test/pg:/data/postgresservices
