name: Deploy to EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Adiciona chave SSH ao runner
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Adiciona o host da EC2 aos conhecidos
        run: |
          ssh-keyscan -H ec2-18-231-183-197.sa-east-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Instala dependências e builda o projeto
        run: |
          yarn
          yarn build

      - name: Copia a pasta dist para a EC2
        run: |
          scp -i ~/.ssh/id_rsa -r dist ubuntu@ec2-18-231-183-197.sa-east-1.compute.amazonaws.com:${{ secrets.PROJECT_PATH }}

      - name: Reinicia aplicação na EC2
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@ec2-18-231-183-197.sa-east-1.compute.amazonaws.com << 'EOF'
            pm2 restart all
          EOF
